### ISSUE TITLE
xocl module is not loaded after installing the XRT package

### ISSUE THREAD

**Issue by haeseung81** [Xilinx/XRT#481]
xocl module is not loaded after installing the XRT package 
You have to manually load the xocl module.

**Comment by mamin506** [comment]
Hi @haeseung81,
In my test, this issue should be fixed in the latest code. Could you double check?

**Comment by stsoe** [comment]
If problem still persists, then please file a CR and provide STR

**Comment by rradjabi** [comment]
@haeseung81 please close this if the issue is stale and won't be tested further.
